// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIR70og-FU184vInidyk1hff7tH4mxD48',
    appId: '1:180139495476:web:367c20a70aa6c974767a61',
    messagingSenderId: '180139495476',
    projectId: 'eunoia-3b894',
    authDomain: 'eunoia-3b894.firebaseapp.com',
    storageBucket: 'eunoia-3b894.firebasestorage.app',
    measurementId: 'G-3TSMPPNPZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkjYDUCNHShnnEjbNORVTmgejYzX3Vgo',
    appId: '1:180139495476:android:673e80ff720a258c767a61',
    messagingSenderId: '180139495476',
    projectId: 'eunoia-3b894',
    storageBucket: 'eunoia-3b894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZ7OjRFvpjdODMS29GnxkmKq_muhQtfo',
    appId: '1:180139495476:ios:ca32742fb9f10c83767a61',
    messagingSenderId: '180139495476',
    projectId: 'eunoia-3b894',
    storageBucket: 'eunoia-3b894.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTZ7OjRFvpjdODMS29GnxkmKq_muhQtfo',
    appId: '1:180139495476:ios:ca32742fb9f10c83767a61',
    messagingSenderId: '180139495476',
    projectId: 'eunoia-3b894',
    storageBucket: 'eunoia-3b894.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIR70og-FU184vInidyk1hff7tH4mxD48',
    appId: '1:180139495476:web:ce3930d7b4743f0b767a61',
    messagingSenderId: '180139495476',
    projectId: 'eunoia-3b894',
    authDomain: 'eunoia-3b894.firebaseapp.com',
    storageBucket: 'eunoia-3b894.firebasestorage.app',
    measurementId: 'G-XFSQFYFR2R',
  );

}